<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'اختیارات ویرایش شدند',
    'Auth item with such name already exists' => 'آیتمی با این نام وجود دارد',
    'Class "{0}" does not exist' => 'کلاس "{0}" وجود ندارد',
    'Classname of the rule associated with this item' => 'کلاس نقش با این آیتم مرتبط شد',
    'Create' => 'ایجاد',
    'Create new permission' => 'ایجاد دسترسی جدید',
    'Create new role' => 'ایجاد نقش جدید',
    'Description' => 'توضیحات',
    'Invalid value' => 'مقدار نامعتبر',
    'Item has been created' => 'آیتم ایجاد شد',
    'Item has been updated' => 'آیتم ویرایش شد',
    'Name' => 'نام',
    'New permission' => 'دسترسی جدید',
    'New role' => 'نقش جدید',
    'New user' => 'کاربر جدید',
    'Permissions' => 'دسترسی ها',
    'Roles' => 'نقش ها',
    'Rule class can not be instantiated' => 'کلاس نقش قابل نمونه سازی نیست',
    'Rule class must extend "yii\rbac\Rule"' => 'کلاس نقش باید از "yii\rbac\Rule" مشتق شود',
    'Rule name' => 'نام نقش',
    'Save' => 'ذخیره',
    'The item description (Optional).' => 'توضیحات آیتم (اختیاری).',
    'The name of the item.' => 'نام آیتم.',
    'There is neither role nor permission with name "{0}"' => 'هیچ گونه نقش یا دستسری با نام "{0}" وجود ندارد',
    'Update assignments' => 'ویرایش اختیارات',
    'Update permission' => 'ویرایش دسترسی',
    'Update role' => 'ویرایش نقش',
    'Users' => 'کاربران',
];
