<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Omistamised muudetud',
    'Auth item with such name already exists' => 'Sellise nimega element on juba olemas',
    'Children' => 'Laps',
    'Class "{0}" does not exist' => 'Klassi "{0}" ei eksisteeri',
    'Create' => 'Loo uus',
    'Create new permission' => 'Tee uus õigus',
    'Create new role' => 'Tee uus roll',
    'Description' => 'Kirjeldus',
    'Invalid value' => 'Vigane väärtus',
    'Item has been created' => 'Element on loodud',
    'Item has been updated' => 'Element on uuendatud',
    'Items' => 'Elemendid',
    'Name' => 'Nimi',
    'New permission' => 'Uus õigus',
    'New role' => 'Uus roll',
    'New user' => 'Uus kasutaja',
    'Permissions' => 'Õigused',
    'Roles' => 'Rollid',
    'Rule' => 'Reegel',
    'Rule class can not be instantiated' => '',
    'Rule class must extend "yii\rbac\Rule"' => 'Reegli klass peab laiendam klassi "yii\rbac\Rule"',
    'Rule name' => 'Reegli nimi',
    'Save' => 'Salvesta',
    'There is neither role nor permission with name "{0}"' => 'Nimega "{0}" ei ole ühtki rolli ega õigust',
    'Update assignments' => 'Muuda omistamisi',
    'Update permission' => 'Muuda õigusi',
    'Update role' => 'Muuda rolli',
    'Users' => 'Kasutajad',
];
