<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Assegnamenti aggiornati',
    'Auth item with such name already exists' => 'Esiste gi&agrave; un oggetto di autenticazione con questo nome',
    'Class "{0}" does not exist' => 'La classe "{0}" non esiste',
    'Classname of the rule associated with this item' => 'Nome della classe della regola associata a questo oggetto',
    'Create' => 'Crea',
    'Create new permission' => 'Crea un nuovo permesso',
    'Create new role' => 'Crea un nuovo ruolo',
    'Description' => 'Descrizione',
    'Invalid value' => 'Valore non valido',
    'Item has been created' => 'Oggetto creato',
    'Item has been updated' => 'Oggetto aggiornato',
    'Name' => 'Nome',
    'New permission' => 'Nuovo permesso',
    'New role' => 'Nuovo ruolo',
    'New user' => 'Nuovo utente',
    'Permissions' => 'Permessi',
    'Roles' => 'Ruoli',
    'Rule class can not be instantiated' => 'Impossibile istanziare la classe delle regole',
    'Rule class must extend "yii\rbac\Rule"' => 'La classe delle regole deve estendere "yii\rbac\Rule"',
    'Rule name' => 'Nome regola',
    'Save' => 'Salva',
    'The item description (Optional).' => 'Descrizione oggetto (opzionale).',
    'The name of the item.' => 'Nome dell\'oggetto',
    'There is neither role nor permission with name "{0}"' => 'Non esiste un ruolo o un permesso di nome "{0}"',
    'Update assignments' => 'Aggiorna assegnamenti',
    'Update permission' => 'Aggiorna permesso',
    'Update role' => 'Aggiorna ruolo',
    'Users' => 'Utenti',
];
