<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Роли были назначены',
    'Auth item with such name already exists' => 'Элемент с таким именем уже существует',
    'Class "{0}" does not exist' => 'Класс "{0}" отсутствует',
    'Classname of the rule associated with this item' => 'Имя класса правил, связанных с этим элементом',
    'Create' => 'Создать',
    'Create new permission' => 'Создать новое разрешение',
    'Create new role' => 'Создать новую роль',
    'Description' => 'Описание',
    'Invalid value' => 'Неверное значение',
    'Item has been created' => 'Пункт был создан',
    'Item has been updated' => 'Пункт был обновлен',
    'Name' => 'Имя',
    'New permission' => 'Новое разрешение',
    'New role' => 'Новая роль',
    'New user' => 'Новый пользователь',
    'Permissions' => 'Разрешения',
    'Roles' => 'Роли',
    'Rule class can not be instantiated' => 'Объект класса правила не может быть создан',
    'Rule class must extend "yii\rbac\Rule"' => 'Класс правил должен быть наследником класса "yii\rbac\Rule"',
    'Rule name' => 'Правило',
    'Save' => 'Сохранить',
    'The item description (Optional).' => 'Описание (Необязательно)',
    'The name of the item.' => 'Имя элемента.',
    'There is neither role nor permission with name "{0}"' => 'Не существует ни ролей ни разрешений с именем "{0}"',
    'Update assignments' => 'Обновление назначения',
    'Update permission' => 'Обновить разрешения',
    'Update role' => 'Обновить роль',
    'Users' => 'Пользователи',
    'Сhildren' => 'Дочерние правила'
];
