<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Se han actualizado las asignaciones',
    'Auth item with such name already exists' => 'Ya existe un elemento con ese nombre',
    'Children' => 'Hijo',
    'Class "{0}" does not exist' => 'La Clase "{0} no existe',
    'Create' => 'Crear',
    'Create new permission' => 'Crear nuevo Permiso',
    'Create new role' => 'Crear nuevo Rol',
    'Description' => 'Descripción',
    'Invalid value' => 'Valor inválido',
    'Item has been created' => 'El elemento ha sido creado',
    'Item has been updated' => 'El elemento ha sido actualizado',
    'Items' => 'Elementos',
    'Name' => 'Nombre',
    'Class' => 'Clase',
    'New permission' => 'Nuevo Permiso',
    'Select permission' => 'Seleccionar permiso',
    'New role' => 'Nuevo Rol',
    'Select role' => 'Seleccionar rol',
    'New user' => 'Nuevo Usuario',
    'New rule' => 'Nueva Regla',
    'Permissions' => 'Permisos',
    'Roles' => 'Roles',
    'Rule' => 'Regla',
    'Select rule' => 'Seleccionar regla',
    'Rules' => 'Reglas',
    'Rule class can not be instantiated' => 'La Regla no puedo ser instanciada',
    'Rule class must extend "yii\rbac\Rule"' => 'La Clase de la Regla debe extender a "yii\rbac\Rule"',
    'Rule name' => 'Nombre de la Regla',
    'Save' => 'Guardar',
    'There is neither role nor permission with name "{0}"' => 'No existe Rol ni Permiso con el nombre "{0}"',
    'Update assignments' => 'Actualizar Asignaciones',
    'Update permission' => 'Actualizar Permiso',
    'Update role' => 'Actualizar Rol',
    'Users' => 'Usuarios',
    'Class' => 'Clase',
    'Created at' => 'Fecha de creación',
    'Enter the description' => 'Ingrese la descripción',
    'Updated at' => 'Última actualización',
];
