<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Las asignaciones han sido actualizadas',
    'Auth item with such name already exists' => 'Ya existe un ítem de autorización con ese nombre',
    'Class "{0}" does not exist' => 'La clase "{0}" no existe',
    'Classname of the rule associated with this item' => 'Nombre de la case de la regla asociada con este ítem',
    'Create' => 'Crear',
    'Create new permission' => 'Crear nuevo permiso',
    'Create new role' => 'Crear nuevo rol',
    'Description' => 'Descripción',
    'Invalid value' => 'Valor inválido',
    'Item has been created' => 'El ítem ha sido creado',
    'Item has been updated' => 'El ítem ha sido actualizado',
    'Name' => 'Nombre',
    'New permission' => 'Nuevo permiso',
    'New role' => 'Nuevo rol',
    'New rule' => 'Nueva regla',
    'New user' => 'Nuevo usuario',
    'Permissions' => 'Permisos',
    'Roles' => 'Roles',
    'Rules' => 'Reglas',
    'Rule class can not be instantiated' => 'La clase "Rule" no puede ser instanciada',
    'Rule class must extend "yii\rbac\Rule"' => 'La clase de la regla debe extender a "yii\rbac\Rule"',
    'Rule name' => 'Nombre de la regla',
    'Save' => 'Guardar',
    'The item description (Optional).' => 'Descripción del ítem (opcional)',
    'The name of the item.' => 'Nombre del ítem',
    'There is neither role nor permission with name "{0}"' => 'No existe rol ni permiso con el nombre "{0}"',
    'Update assignments' => 'Actualizar asignaciones',
    'Update permission' => 'Actualizar permiso',
    'Update role' => 'Actualizar rol',
    'Users' => 'Usuarios',
    'Сhildren' => 'Hijos'
];
