<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 *
 * @author Pablo Palacios
 * @email pp@moplin.com
 *
 */
return [
    'Children' => 'Hijos',
    'Items' => 'Ítems',
    'Rule' => 'Regla',
    'Rules' => 'Reglas',
    'Rule class must extend "yii\rbac\Rule"' => 'La Clase de la regla debe extender "yii\rbac\Rule"',
    'Classname of the rule associated with this item' => 'Nombre de clase de la regla asociada con este ítem',
    'The item description (Optional).' => 'La descripción del Ítem (Opcional).',
    'The name of the item.' => 'Nombre del ítem.',
    'Assignments have been updated' => 'Se han actualizado las asignaciones',
    'Auth item with such name already exists' => 'El artículo de autenticación con ese nombre ya existe',
    'Class "{0}" does not exist' => ' "La Clase "{0}" no existe ',
    'Create' => 'Crear',
    'Create new permission' => 'Crear un nuevo permiso',
    'Create new role' => 'Crear un nuevo rol',
    'Description' => 'Descripción',
    'Invalid value' => 'Valor incorrecto',
    'Item has been created' => 'El Ítem se ha creado',
    'Item has been updated' => 'El Ítem se ha actualizado',
    'Name' => 'Nombre',
    'New permission' => 'Nuevo permiso',
    'New role' => 'Nuevo rol',
    'New rule' => 'Nueva regla',
    'New user' => 'Nuevo usuario',
    'Permissions' => 'Permisos',
    'Select permission' => 'Selecciona el permiso',
    'Roles' => 'Roles',
    'Rule class can not be instantiated' => 'La clase de regla no se puede instanciar',
    'Rule name' => 'Nombre de la regla',
    'Save' => 'Guardar',
    'There is neither role nor permission with name "{0}"' => 'No hay rol ni permiso con nombre "{0}"',
    'Update assignments' => 'Actualizar las asignaciones',
    'Update permission' => 'Actualizar los permisos',
    'Update role' => 'Actualizar el rol',
    'Users' => 'Usuarios',
    'Enter the description' => 'Escriba una descripción',
    'Select role' => 'Seleccione un rol',
    'Select rule' => 'Seleccione una regla',
    'Class' => 'Clase',
    'Created at' => 'Creado el',
    'Updated at' => 'Actualizado el',
];
