<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => '已经重新分配',
    'Auth item with such name already exists' => '该名称已经存在',
    'Children' => '子',
    'Class "{0}" does not exist' => 'Class "{0}" 不存在',
    'Classname of the rule associated with this item' => '与该 rule 相关的类名',
    'Create' => '创建',
    'Create new permission' => '创建新权限',
    'Create new role' => '创建新角色',
    'Description' => '描述',
    'Invalid value' => '无效的值',
    'Item has been created' => '创建成功',
    'Item has been updated' => '已经更新',
    'Items' => '主题',
    'Name' => '名称',
    'New permission' => '创建权限',
    'New role' => '创建角色',
    'New user' => '创建新用户',
    'Permissions' => '权限',
    'Roles' => '角色',
    'Rule' => '规则',
    'Rule class can not be instantiated' => 'Rule class 不能被实例化',
    'Rule class must extend "yii\rbac\Rule"' => 'Rule class 必须继承自 "yii\rbac\Rule"',
    'Rule name' => '规则名称',
    'Save' => '保存',
    'The item description (Optional).' => '该项描述（补充）',
    'The name of the item.' => '该项的名称',
    'There is neither role nor permission with name "{0}"' => 'name"{0}"既不是角色也不是权限',
    'Update assignments' => '修改指定',
    'Update permission' => '修改权限',
    'Update role' => '修改角色',
    'Users' => '用户',
];
