<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => '分配已更新',
    'Auth item with such name already exists' => '此名称的认证项已经存在',
    'Class "{0}" does not exist' => '类 "{0}" 不存在',
    'Classname of the rule associated with this item' => '与此项关联的规则类名',
    'Create' => '创建',
    'Create new permission' => '创建新权限',
    'Create new role' => '创建新角色',
    'Description' => '描述',
    'Invalid value' => '无效值',
    'Item has been created' => '项目已被创建',
    'Item has been updated' => '项目已被更新',
    'Name' => '名字',
    'New permission' => '新权限',
    'New role' => '新角色',
    'New user' => '新用户',
    'Permissions' => '权限',
    'Roles' => '角色',
    'Rule class can not be instantiated' => '规则类不能被实例化',
    'Rule class must extend "yii\rbac\Rule"' => '规则类必须继承自 "yii\rbac\Rule"',
    'Rule name' => '规则名',
    'Save' => '保存',
    'The item description (Optional).' => '项目描述 (可选)',
    'The name of the item.' => '项目名。',
    'There is neither role nor permission with name "{0}"' => '没有 "{0}" 的规则和权限',
    'Update assignments' => '修改授权',
    'Update permission' => '修改权限',
    'Update role' => '修改角色',
    'Users' => '用户',
    'Rule' => '规则',
    'Children' => '子项',
];
