<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Children' => '子类',
    'Items' => '事项',
    'Rule' => '规则',
    'Rule class must extend "yii\rbac\Rule"' => '规则类必须继承于"yii\rbac\Rule"',
    'Classname of the rule associated with this item' => '事项相关的规则类名',
    'The item description (Optional).' => '事项描述（可选）',
    'The name of the item.' => '事项名称',
    'Assignments have been updated' => '授权已经更新',
    'Auth item with such name already exists' => '同名事项已经存在',
    'Class "{0}" does not exist' => '{0}类不存在',
    'Create' => '创建',
    'Create new permission' => '创建新权限',
    'Create new role' => '创建新角色',
    'Description' => '描述',
    'Invalid value' => '赋值不正确',
    'Item has been created' => '事项已创建',
    'Item has been updated' => '事项已更新',
    'Name' => '名称',
    'New permission' => '新权限',
    'New role' => '新角色',
    'New user' => '新用户',
    'Permissions' => '权限',
    'Roles' => '角色',
    'Rule class can not be instantiated' => '规则类不可以实例化',
    'Rule name' => '规则名称',
    'Save' => '保存',
    'There is neither role nor permission with name "{0}"' => '当前没有名为"{0}"的角色或者权限。',
    'Update assignments' => '更新授权',
    'Update permission' => '更新权限',
    'Update role' => '更新角色',
    'Users' => '用户',
];
