<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => '',
    'Auth item with such name already exists' => '',
    'Class "{0}" does not exist' => '',
    'Classname of the rule associated with this item' => '',
    'Create' => '',
    'Create new permission' => '',
    'Create new role' => '',
    'Description' => '',
    'Invalid value' => '',
    'Item has been created' => '',
    'Item has been updated' => '',
    'Name' => '',
    'New permission' => '',
    'New role' => '',
    'New user' => '',
    'Permissions' => '',
    'Roles' => '',
    'Rule class can not be instantiated' => '',
    'Rule class must extend "yii\rbac\Rule"' => '',
    'Rule name' => '',
    'Save' => '',
    'The item description (Optional).' => '',
    'The name of the item.' => '',
    'There is neither role nor permission with name "{0}"' => '',
    'Update assignments' => '',
    'Update permission' => '',
    'Update role' => '',
    'Users' => '',
];
