<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Children' => 'Children',
    'Items' => 'รายการ (Items)',
    'Rule' => 'กฎ (Rule)',
    'Rule class must extend "yii\rbac\Rule"' => 'Rule class must extend "yii\rbac\Rule"',
    'Classname of the rule associated with this item' => 'ชื่อคลาสของกฎที่เกี่ยวข้องกับรายการนี้',
    'The item description (Optional).' => 'คำอธิบายรายการ (ไม่บังคับ)',
    'The name of the item.' => 'ชื่อของรายการ (Items)',
    'Assignments have been updated' => 'ที่ได้รับการปรับปรุง',
    'Auth item with such name already exists' => 'มีรายการที่มีชื่อดังกล่าวอยู่แล้ว',
    'Class "{0}" does not exist' => 'คลาส "{0}" ไม่มีอยู่',
    'Create' => 'สร้าง',
    'Create new permission' => 'สร้างสิทธิ์ใหม่ (Permission)',
    'Create new role' => 'สร้างบทบาทใหม่ (Role)',
    'Description' => 'คำอธิบาย',
    'Invalid value' => 'ค่าไม่ถูกต้อง',
    'Item has been created' => 'สร้างรายการแล้ว',
    'Item has been updated' => 'อัพเดทรายการแล้ว',
    'Name' => 'ชื่อ',
    'New permission' => 'สร้างสิทธิ์การเข้าถึงใหม่ (Permission)',
    'New role' => 'สร้างบทบาทใหม่ (Role)',
    'New user' => 'สร้างผู้ใช้ใหม่ (User)',
    'Permissions' => 'สิทธิ์',
    'Roles' => 'บทบาท',
    'Rule class can not be instantiated' => 'ไม่สามารถสร้างอินสแตนซ์คลาสของกฎได้',
    'Rule name' => 'ชื่อกฎ (Role)',
    'Save' => 'บันทึก',
    'There is neither role nor permission with name "{0}"' => 'ไม่มีทั้งบทบาทหรือการอนุญาตที่มีชื่อ "{0}"',
    'Update assignments' => 'อัปเดตงานแล้ว (Assignments)',
    'Update permission' => 'อัปเดตสิทธิ์แล้ว (Permission)',
    'Update role' => 'อัปเดตกฎแล้ว (Role)',
    'Users' => 'ผู้ใช้ (User)',
];
