<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Les affectations ont été mises à jour',
    'Auth item with such name already exists' => 'L\'objet de Auth avec un nom identique existe déjà',
    'Children' => 'Enfants',
    'Class "{0}" does not exist' => 'La classe "{0}" n\'existe pas',
    'Classname of the rule associated with this item' => 'Le nom de la classe de la règle associée à cet objet',
    'Create' => 'Créer',
    'Create new permission' => 'Créer nouvelle permission',
    'Create new role' => 'Créer nouveau rôle',
    'Description' => 'Description',
    'Invalid value' => 'Valeur invalide',
    'Item has been created' => 'Objet a été crée',
    'Item has been updated' => 'Objet a été mis à jour',
    'Items' => 'Objets',
    'Name' => 'Nom',
    'New permission' => 'Nouvelle permission',
    'New role' => 'Nouveau rôle',
    'New user' => 'Nouvel utilisateur',
    'Permissions' => 'Permissions',
    'Roles' => 'Rôles',
    'Rule' => 'Règle',
    'Rule class can not be instantiated' => 'La classe de règle ne peut pas être instanciée',
    'Rule class must extend "yii\rbac\Rule"' => 'La classe de règle doit étendre "yii\rbac\Rule"',
    'Rule name' => 'Nom de la règle',
    'Save' => 'Sauvegarder',
    'The item description (Optional).' => 'La description de l\'objet (Facultatif)',
    'The name of the item.' => 'Le nom de l\'objet.',
    'There is neither role nor permission with name "{0}"' => 'Il n\'y a ni rôle, ni l\'autorisation avec le nom "{0}"',
    'Update assignments' => 'Modifier affectations',
    'Update permission' => 'Modifier permission',
    'Update role' => 'Modifier rôle',
    'Users' => 'Utlisateurs',
];
