<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Children' => '子類',
    'Items' => '事項',
    'Rule' => '規則',
    'Rule class must extend "yii\rbac\Rule"' => '規則類必須繼承于"yii\rbac\Rule"',
    'Classname of the rule associated with this item' => '事項相關的規則類名',
    'The item description (Optional).' => '事項描述（可選）',
    'The name of the item.' => '事項名稱',
    'Assignments have been updated' => '授權已經更新',
    'Auth item with such name already exists' => '同名事項已經存在',
    'Class "{0}" does not exist' => '{0}類不存在',
    'Create' => '創建',
    'Create new permission' => '創建新權限',
    'Create new role' => '創建新角色',
    'Description' => '描述',
    'Invalid value' => '賦值不正確',
    'Item has been created' => '事項已創建',
    'Item has been updated' => '事項已更新',
    'Name' => '名稱',
    'New permission' => '新權限',
    'New role' => '新角色',
    'New user' => '新用戶',
    'Permissions' => '權限',
    'Roles' => '角色',
    'Rule class can not be instantiated' => '規則類不可以實例化',
    'Rule name' => '規則名稱',
    'Save' => '保存',
    'There is neither role nor permission with name "{0}"' => '當前沒有名爲"{0}"的角色或者權限。',
    'Update assignments' => '更新授權',
    'Update permission' => '更新權限',
    'Update role' => '更新角色',
    'Users' => '用戶',
];
