<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'De toewijzing is bijgewerkt',
    'Auth item with such name already exists' => 'Er bestaat al een Auth item met dezelfde naam',
    'Children' => '',
    'Class "{0}" does not exist' => 'De classe "{0}" bestaat niet',
    'Classname of the rule associated with this item' => 'Classe naam van de regel gekoppeld aan dit item',
    'Create' => 'Aanmaken',
    'Create new permission' => 'Nieuwe toestemming aanmaken',
    'Create new role' => 'Nieuwe rol aanmaken',
    'Description' => 'Omschrijving',
    'Invalid value' => 'Ongeldige input',
    'Item has been created' => 'Het item is aangemaakt',
    'Item has been updated' => 'Het item is bijgewerkt',
    'Items' => 'Items',
    'Name' => 'Naam',
    'New permission' => 'Nieuwe toestemming',
    'New role' => 'Nieuwe rol',
    'New user' => 'Nieuwe gebruiker',
    'Permissions' => 'Toestemmingen',
    'Roles' => 'Rollen',
    'Rule' => 'Rol',
    'Rule class can not be instantiated' => 'Rol classe kan niet worden geïnstantieerd',
    'Rule class must extend "yii\rbac\Rule"' => 'Rol classe moet overerven van "yii\rbac\Rule"',
    'Rule name' => 'Rol naam',
    'Save' => 'Opslaan',
    'The item description (Optional).' => 'Item omschrijving (optioneel)',
    'The name of the item.' => 'Naam van het item.',
    'There is neither role nor permission with name "{0}"' => 'Er is geen rol of permissie met de naam "{0}"',
    'Update assignments' => 'Toewijzing bijwerken',
    'Update permission' => 'Toestemming bijwerken',
    'Update role' => 'Rol bijwerken',
    'Users' => 'Gebruikers',
];
