<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Die Zuordnungen wurden gespeichert',
    'Auth item with such name already exists' => 'Ein Element mit diesem Namen existiert bereits',
    'Children' => 'Kind',
    'Class "{0}" does not exist' => 'Die Klasse "{0} existiert nicht',
    'Create' => 'Erstellen',
    'Create new permission' => 'Neue Berechtigung erstellen',
    'Create new role' => 'Neue Rolle erstellen',
    'Description' => 'Beschreibung',
    'Invalid value' => 'Ungültiger Wert',
    'Item has been created' => 'Das Element wurde erstellt',
    'Item has been updated' => 'Das Element wurde gespeichert',
    'Items' => 'Elemente',
    'Name' => 'Name',
    'New permission' => 'Neue Berechtigung',
    'New role' => 'Neue Rolle',
    'New user' => 'Neuer Benutzer',
    'Permissions' => 'Berechtigungen',
    'Roles' => 'Rollen',
    'Rule' => 'Regel',
    'Rule class can not be instantiated' => 'Die Regelklasse kann nicht instanziiert werden',
    'Rule class must extend "yii\rbac\Rule"' => 'Die Regelklasse muss "yii\rbac\Rule" erweitern',
    'Rule name' => 'Regelname',
    'Save' => 'Speichern',
    'There is neither role nor permission with name "{0}"' => 'Es gibt weder eine Regel noch eine Berechtigung mit dem Namen "{0}"',
    'Update assignments' => 'Zuordnungen speichern',
    'Update permission' => 'Berechtigung speichern',
    'Update role' => 'Rolle speichern',
    'Users' => 'Benutzer',
];
