<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Rule class must extend "yii\rbacRule"' => 'Lớp định nghĩa Quy định phải kế thừa từ lớp "yii\rbacRule"',    'Assignments have been updated' => 'Đã gán quyền thành công',
    'Auth item with such name already exists' => 'Phân quyền đã tồn tại',
    'Children' => 'Quyền liên quan',
    'Class' => 'Lớp',
    'Class "{0}" does not exist' => 'Lớp "{0}" không tồn tại',
    'Create' => 'Tạo mới',
    'Create new permission' => 'Tạo Quyền mới',
    'Create new role' => 'Tạo Vai trò mới',
    'Create rule' => 'Tạo Quy định mới',
    'Created at' => 'Thời gian Tạo',
    'Data cannot be decoded' => 'Dữ liệu không thể được giải mã',
    'Data must be type of JSON ({0})' => 'Dữ liệu phải là định dạng JSON ({0})',
    'Description' => 'Mô tả',
    'Enter the description' => 'Nhập mô tả',
    'Invalid value' => 'Giá trị không hợp lệ',
    'Item has been created' => 'Đã tạo phân quyền',
    'Item has been updated' => 'Đã sửa phân quyền',
    'Items' => 'Phân quyền',
    'Name' => 'Tên',
    'Name is already in use' => 'Tên này đã được sử dụng',
    'New permission' => 'Quyền mới',
    'New role' => 'Vai trò mới',
    'New rule' => 'Quy định mới',
    'New user' => 'Người dùng mới',
    'Not found' => 'Không tìm thấy',
    'Permissions' => 'Quyền',
    'Roles' => 'Vai trò',
    'Rule' => 'Quy định',
    'Rule class can not be instantiated' => 'Lớp định nghĩa Quy định không thể được khởi tạo',
    'Rule has been added' => 'Đã thêm Quy định',
    'Rule has been removed' => 'Đã xóa Quy định',
    'Rule has been updated' => 'Đã sửa Quy định',
    'Rule name' => 'Tên Quy định',
    'Rule {0} does not exist' => 'Quy định {0} không tồn tại',
    'Rules' => 'Quy định',
    'Save' => 'Lưu',
    'Select permission' => 'Chọn Quyền',
    'Select role' => 'Chọn Vai trò',
    'Select rule' => 'Chọn Quy định',
    'There is neither role nor permission with name "{0}"' => 'Không có vai trò hay Quy định nào với tên "{0}"',
    'Update assignments' => 'Sửa Cấp quyền',
    'Update permission' => 'Sửa Quyền',
    'Update role' => 'Sửa Vai trò',
    'Update rule' => 'Sửa Quy định',
    'Updated at' => 'Thời gian sửa',
    'Users' => 'Người dùng',
];
