<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Children' => 'Дочірні правила',
    'Items' => ' Pozycja',
    'Rule' => 'Reguła',
    'Rule class must extend "yii\rbac\Rule"' => 'Klasa reguły musi dziedziczyć po "yii\rbac\Rule"',
    'Classname of the rule associated with this item' => 'Klasa reguły powiązana z pozycją',
    'The item description (Optional).' => 'Opis pozycji (Opcjonalnie).',
    'The name of the item.' => 'Nazwa pozycji.',
    'Assignments have been updated' => 'Przypisanire zostało zaktualizowane',
    'Auth item with such name already exists' => 'Pozycja o takiej samej nazwie już istnieje',
    'Class "{0}" does not exist' => 'Klasa "{0}" nie istnieje',
    'Create' => 'Utwótrz',
    'Create new permission' => 'Utwótrz nowe uprawnienia',
    'Create new role' => 'Utwórz nową rolę',
    'Description' => 'Opis',
    'Invalid value' => 'Nieprawidłowa wartość',
    'Item has been created' => 'Pozycja została stworzona',
    'Item has been updated' => 'Pozycja została zaktualizowana',
    'Name' => 'Nazwa',
    'New permission' => 'Nowe uprawnienia',
    'New role' => 'Nowa rola',
    'New user' => 'Nowy użytkownik',
    'Permissions' => 'Uprawnienia',
    'Roles' => 'Role',
    'Rule class can not be instantiated' => 'Reguła klasy została zaktualizowana',
    'Rule name' => 'Nazwa reguły',
    'Save' => 'Zapisz',
    'There is neither role nor permission with name "{0}"' => 'Rola ani uprawnienie o nazwie "{0}" nie istnieją',
    'Update assignments' => 'Aktualizacja przypisania',
    'Update permission' => 'Aktualizacja uprawnień',
    'Update role' => 'Aktualizuj role',
    'Users' => 'Użytkownicy',
];
