<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'As atribuições foram atualizadas',
    'Auth item with such name already exists' => 'O item Auth com este nome já existe',
    'Children' => 'Descendentes',
    'Class "{0}" does not exist' => 'A classe "{0}" não existe',
    'Classname of the rule associated with this item' => 'Nome da classe da regra associada a este item',
    'Create' => 'Criar',
    'Create new permission' => 'Criar nova permissão',
    'Create new role' => 'Criar nova role',
    'Description' => 'Descrição',
    'Invalid value' => 'Valor inválido',
    'Item has been created' => 'Item foi criado',
    'Item has been updated' => 'Item foi atualizado',
    'Name' => 'Nome',
    'New permission' => 'Nova permissão',
    'New role' => 'Nova role',
    'New user' => 'Novo usuário',
    'Permissions' => 'Permissões',
    'Roles' => 'Roles',
    'Rule' => 'Regra',
    'Rule class can not be instantiated' => 'A classe de regra não pode ser instanciada',
    'Rule class must extend "yii\rbac\Rule"' => 'A classe de regra deve estender "yii\rbac\Rule"',
    'Rule name' => 'Nome da regra',
    'Save' => 'Salvar',
    'The item description (Optional).' => 'Descrição do item (Opcional).',
    'The name of the item.' => 'Nome do item.',
    'There is neither role nor permission with name "{0}"' => 'Não existe nem role nem permissão com o nome "{0}"',
    'Update assignments' => 'Alterações realizadas',
    'Update permission' => 'Alterar permissão',
    'Update role' => 'Alterar role',
    'Users' => 'Usuários',
];
