<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Lomas ir atjaunotas',
    'Auth item with such name already exists' => 'Elements ar tādu vārdu jau eksistē',
    'Class "{0}" does not exist' => 'Šāda klase "{0}" neeksistē',
    'Classname of the rule associated with this item' => 'Lomu klase, kas tiek, piesaistīta šim elimentam',
    'Create' => 'Izveidot',
    'Create new permission' => 'Izveidot jaunas tiesības',
    'Create new role' => 'Izveidot jaunu lomu',
    'Description' => 'Apraksts',
    'Invalid value' => 'Kļūdaina vērtība',
    'Item has been created' => 'Postenis ir izveidots',
    'Item has been updated' => 'Postenis ir atjaunots',
    'Name' => 'Vārds',
    'New permission' => 'Jauna tiesība',
    'New role' => 'Jauna loma',
    'New user' => 'Jauns lietotājs',
    'Permissions' => 'Tiesības',
    'Roles' => 'Lomas',
    'Rule class can not be instantiated' => 'Lomu klasi nevar izveidot',
    'Rule class must extend "yii\rbac\Rule"' => 'Lomas klase ir jāveido no klases "yii\rbac\Rule"',
    'Rule name' => 'Lomas nosaukums',
    'Save' => 'Saglabāt',
    'The item description (Optional).' => 'Apraksts (Neobligāts)',
    'The name of the item.' => 'Elementa nosaukums.',
    'There is neither role nor permission with name "{0}"' => 'Neksistē šādas lomas vai tiesības "{0}"',
    'Update assignments' => 'Atjauninājumi uzstādīti',
    'Update permission' => 'Atjaunot uzstādījumus',
    'Update role' => 'Atjaunot lomu',
    'Users' => 'Lietotājs',
    'Сhildren' => 'Apakšlomas'
];
